### ISSUE TITLE
Add simple integration test

### ISSUE THREAD

**Issue by jupp0r** [jupp0r/prometheus-cpp#2]
It would be really beneficial to have a simple integration test that tests whether prometheus can scrape the sample server:

1. bulid and start sample_server
2. start prometheus with a suitable config (see below)
3. wait a few seconds for prometheus to boot and scrape
4. query the prometheus REST API to check if metrics are present

```yaml
  scrape_configs:
  - job_name: 'static'
    scrape_interval: '1s'
    static_configs:
      - targets:
          - 'localhost:8080'
```
